### PR TITLE
Add support for doors and lifts

### PR DESCRIPTION
**Pull request by koonpeng**
### Implemented feature

Adds support for doors and lifts, also fixes a bunch of picking related bugs.

Some of the bugs fixes are:
* Objects still being selected when they are behind a egui widget.
* Some objects like walls that respawn their meshes losing their highlights.
* Unnecesssary extra traversal of the entity hierarchy when making meshes pickable.
* Camera mode keyboard shortcuts not being disabled when editing a text field.

### CODE REVIEW

**Review by mayman99 — APPROVED** [review]
I did run it and lifts seem to be okay :+1: 
p.s. didn't review code as I didn't have a chance to read on rust yet

**Comment by luca-della-vedova** [comment]
I can't quite get the JSON input to work properly, it seems whatever I write is always considered "invalid json", i.e.:

https://user-images.githubusercontent.com/9111558/179193506-37872ae1-9da3-4e78-b087-a77cdcbc74ce.mp4

I'm not too sure how to debug it, I added a print statement to the `value_json` parameter that is passed to the function and saw the following (example):

```
Value is "{\n\"test\": 123\n}"
```

I'm not sure if it's intended behavior of the debug printer but I find the escaping of `"` a bit suspicious and I can see why a json parser would fail if it tried to read that string. I wonder if the escaping is happening the scenes and that might cause the json parser to fail.
I also tried to get rid of json altogether and use yaml (imho preferred option to avoid adding another dependency just for a temporary feature until we have a better UI to set lift doors) but I had a missing trait error and I'm not familiar enough with rust to figure out what might be happening. I noticed that the function signature for [serde_yaml::from_str](https://docs.serde.rs/serde_yaml/fn.from_str.html) and [serde_json::from_str](https://docs.serde.rs/serde_json/fn.from_str.html) are slightly different so I guess the reason might be there.

```
luca@luxury:~/ws_sim/rmf_sandbox/rmf_sandbox$ cargo run
   Compiling rmf_sandbox v0.0.1 (/home/luca/ws_sim/rmf_sandbox/rmf_sandbox)
error[E0277]: the trait bound `for<'de> T: Deserialize<'de>` is not satisfied
    --> src/widgets.rs:36:19
     |
36   |             match serde_yaml::from_str::<T>(self.value_json.as_str()) {
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'de> Deserialize<'de>` is not implemented for `T`
     |
     = note: required because of the requirements on the impl of `DeserializeOwned` for `T`
note: required by a bound in `serde_yaml::from_str`
    --> /home/luca/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.23/src/de.rs:1445:8
     |
1445 |     T: DeserializeOwned,
     |        ^^^^^^^^^^^^^^^^ required by this bound in `serde_yaml::from_str`
help: consider further restricting this bound
     |
26   |     T: Deserialize<'de> + Serialize + for<'de> building_map::_::_serde::Deserialize<'de>,
     |                                     ++++++++++++++++++++++++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rmf_sandbox` due to previous error
```

**Comment by koonpeng** [comment]
> I can't quite get the JSON input to work properly, it seems whatever I write is always considered "invalid json", i.e.:

The validator follows the format of the building yaml file, an example can be found here.

https://github.com/open-rmf/rmf_demos/blob/9cf5b279ae22f04ac5cd81a5bbcda9eb5ec404b8/rmf_demos_maps/maps/hotel/hotel.building.yaml#L1030-L1036

> I also tried to get rid of json altogether and use yaml (imho preferred option to avoid adding another dependency just for a temporary feature until we have a better UI to set lift doors) but I had a missing trait error and I'm not familiar enough with rust to figure out what might be happening. I noticed that the function signature for [serde_yaml::from_str](https://docs.serde.rs/serde_yaml/fn.from_str.html) and [serde_json::from_str](https://docs.serde.rs/serde_json/fn.from_str.html) are slightly different so I guess the reason might be there.

`serde_yaml` requires a `DeserializeOwned` instead of `Deserialize`, try changing the template constraints and see if it works.

**Comment by koonpeng** [comment]
I remembered the reason why `serde_json` was used instead of `serde_yaml`. When converting the object to the string representation, I want it to use the json format. `serde_yaml::to_string()` converts to the yaml format and I couldn't find anyway to tell it to use the json representation.

**Review by mxgrey — APPROVED** [review]

**Pull request merged**
